SistemaWeb/Controllers/EquipoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaWeb.Data;
using SistemaWeb.Models;

namespace SistemaWeb.Controllers
{
	public class EquipoController : Controller
	{
			SP_Equipo _Equipo = new SP_Equipo();
            private readonly SP_Estatus _estatus;
            private readonly SP_Resguardo _resguardo;
            private readonly SP_Select_Empleado _empleado;
            private readonly SP_Office _office;
            private readonly SP_Procesador _procesador;
            private readonly SP_Ram _ram;

        public EquipoController(SP_Estatus estatus, SP_Resguardo resguardo, SP_Select_Empleado empleado, SP_Office office, SP_Procesador procesador, SP_Ram ram)
        {
            _estatus = estatus;
            _resguardo = resguardo;
            _empleado = empleado;
            _office = office;
            _procesador = procesador;
            _ram = ram;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult EquipoLista() 
		{

            if (HttpContext.Session.GetString("Usuario") == null)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                String user = HttpContext.Session.GetString("User") ?? string.Empty;
                int userId = HttpContext.Session.GetInt32("UserId") ?? 0;

                // Puedes hacer lo que necesites con el ID del usuario, por ejemplo, pasarlo a la vista
                ViewBag.UserId = userId;
                ViewBag.Usuario = user;

                List<EstatusModel> estatus = _estatus.ObtenerEstatus();
                ViewBag.Estatus = estatus;
                List<ResguardoModel> resguardo = _resguardo.ObtenerResguardo();
                ViewBag.Resguardo = resguardo;
                List<SelectEmpleadoModel> empleado = _empleado.ObtenerEmpleado();
                ViewBag.Empleado = empleado;
                List<OfficeModel> office = _office.ObtenerOffice();
                ViewBag.Office = office;
                List<ProcesadorModel> procesador = _procesador.ObtenerProcesador();
                ViewBag.Procesador = procesador;
                List<RamModel> ram = _ram.ObtenerRam();
                ViewBag.Ram = ram;

                var oLista = _Equipo.Listar();
                return View(oLista);
            }

        }

        public IActionResult UsuarioView()// solo devuelve la vista
			{
				return View();
			}

        [HttpPost]
        public IActionResult Guardar([FromBody] EquipoModel oEquipo)
        {
            int userId = HttpContext.Session.GetInt32("UserId") ?? 0; // Obtener el ID de usuario de la sesión

            // Establecer userId en el modelo de empleado
        
            try
            {
                var (exito, mensaje) = _Equipo.Insertar(oEquipo);

                if (exito)
                {
                    return Json(new { success = true, message = mensaje });
                }
                else
                {
                    return Json(new { success = false, message = mensaje });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Error al procesar la solicitud: " + ex.Message });
            }
        }


        [HttpGet]
        public IActionResult ObtenerEquipo(int idEquipo)
        {
            int userId = HttpContext.Session.GetInt32("UserId") ?? 0;
            var equipo = _Equipo.Obtener(idEquipo);

            if (equipo != null)
            {
                return Json(equipo);
            }
            else
            {
                return Json(new { error = "Equipo no encontrado" });
            }
        }

        [HttpGet]
        public IActionResult ObtenerEquipo2(int idEquipo)
        {
            int userId = HttpContext.Session.GetInt32("UserId") ?? 0;
            var empleado = _Equipo.Obtener2(idEquipo);

            if (empleado != null)
            {
                return Json(empleado);
            }
            else
            {
                return Json(new { error = "Equipo no encontrado" });
            }
        }
        [HttpPost]
        public IActionResult ActualizarEquipo(EquipoModel oEquipo)
        {
            //int userId = HttpContext.Session.GetInt32("UserId") ?? 0; // Obtener el ID de usuario de la sesión

            // Establecer userId en el modelo de usuario
            //oEmpleado.Usuario_Alta = userId;
            try
            {
                var (exito, mensaje) = _Equipo.Editar(oEquipo);

                if (exito)
                {

                    return Json(new { success = true, message = mensaje });

                }
                else
                {
                    return Json(new { success = false, message = mensaje });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Error al procesar la solicitud: " + ex.Message });
            }
        }
    }
	}

SistemaWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemaWeb.Models;
using SistemaWeb.Permisos;
using System.Diagnostics;

namespace SistemaWeb.Controllers
{
    [ValidarSession]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Response.Headers.Add("Cache-Control", "no-cache, no-store, must-revalidate");
            Response.Headers.Add("Pragma", "no-cache");
            Response.Headers.Add("Expires", "0");
			String user = HttpContext.Session.GetString("User") ?? string.Empty;
			int userId = HttpContext.Session.GetInt32("UserId") ?? 0;

			// Pasar el Id_Usuario a la vista
			ViewBag.IdUsuario = userId;
            ViewBag.Usuario = user; ;
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="~/css/carga.css" rel="stylesheet" />
	<title>Home</title>
</head>
<body>
	<div class="preloader">
		<div class="text-container">
			<div class="letter" style="color: #7FA644;">G</div>
			<div class="letter" style="color: #737373;">R</div>
			<div class="letter" style="color: #A6BF6F;">U</div>
			<div class="letter" style="color: #8C8C8C;">P</div>
			<div class="letter" style="color: #7FA644;">A</div>
			<div class="letter" style="color: #737373;">K</div>
		</div>
		<div class="circle-container">
			<div class="circle" style="background-color: #7FA644;"></div>
			<div class="circle" style="background-color: #737373;"></div>
			<div class="circle" style="background-color: #A6BF6F;"></div>
			<div class="circle" style="background-color: #8C8C8C;"></div>
		</div>
	</div>

	<!-- Page content -->
	<!-- Page header -->
	<br />
	<div class="container">
		<div class="row">
			<div class="col" style="text-align:center">
				<a asp-controller="Equipo" asp-action="EquipoLista" class="card-link text-decoration-none" style="color:black">
					<div class="card text-white mb-4" style="background-color:#A6BF6F">
						<div class="card-body">
							<h4 class="card-title">Equipos</h4>
							<i class="fas fa-solid fa-laptop fa-2xl" style="padding: 20px"></i>
						</div>
					</div>
				</a>
			</div>
			<div class="col" style="text-align:center">
				<a asp-controller="Empleado" asp-action="EmpleadoLista" class="card-link text-decoration-none" style="color:black">
					<div class="card text-white mb-4" style="background-color:#A6BF6F">
						<div class="card-body">
							<h4 class="card-title">Empleados</h4>
							<i class="fas fa-users fa-fw fa-2xl" style="padding: 20px"></i>
						</div>
					</div>
				</a>
			</div>
			<div class="col" style="text-align:center">
				<a asp-controller="EquipoBaja" asp-action="EquipoBaja" class="card-link text-decoration-none" style="color:black">
					<div class="card text-white mb-4" style="background-color:#A6BF6F">
						<div class="card-body">
							<h4 class="card-title">Baja Equipos </h4>
							<i class="fas fa-arrow-alt-circle-down fa-fw fa-2xl" style="padding: 20px"></i>
						</div>
					</div>
				</a>
			</div>
			<div class="col" style="text-align:center">
				<a asp-controller="Usuarios" asp-action="Listar" class="card-link text-decoration-none" style="color:black">
					<div class="card text-white mb-4" style="background-color:#A6BF6F">
						<div class="card-body">
							<h4 class="card-title">Usuarios</h4>
							<i class="fas fa-solid fa-circle-user fa-2xl" style="padding: 20px"></i>
						</div>
					</div>
				</a>
			</div>
		</div>
	</div>

	<br />
	@* 	carrusel
	inicio*@

	<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel" style="text-align:center">
		<div class="carousel-indicators">
			<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
			<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
			<button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
		</div>
		<div class="carousel-inner">
			<div class="carousel-item active" data-bs-interval="10000">
				<img src="https://www...com.mx/images/proveedor_carton_corrugado.jpg" class="d-block w-100" alt="imagen" style="width:300px; height:500px">
				<div class="carousel-caption d-none d-md-block">
					<h5 class="text-white bg-dark"> ¿Quiénes somos? </h5>
					<p class="font-monospace  text-white bg-dark">
						En , estamos orgullosos de ser una empresa 100% mexicana con más de <br>
						60 años de experiencia, ofreciendo calidad en nuestros productos y servicios, <br>
						respaldados por nuestro liderazgo y amplia experiencia en las industrias de fibra, <br>
						papel y cartón corrugado.
					</p>
				</div>
			</div>
			<div class="carousel-item" data-bs-interval="2000">
				<img src="https://www...com.mx/images/bodega_papel_reciclado.jpg" class="d-block w-100" alt="..." style="width:300px; height:500px">
				<div class="carousel-caption d-none d-md-block">
					<h5 class="text-white bg-dark">Misión</h5>
					<p class="font-monospace text-white bg-dark">
						Ser el Grupo líder en sustentabilidad dentro de nuestro sector, que <br>
						proporcione soluciones vanguardistas de papel y empaque para nuestros clientes, <br>
						teniendo como prioridad el desarrollo del talento humano, y el compromiso con los <br>
						valores organizacionales.
					</p>
				</div>
			</div>
			<div class="carousel-item">
				<img src="https://www...com.mx/images/cajas_carton_corrugado_mayorista.jpg" class="d-block w-100" alt="..." style="width:300px; height:500px">
				<div class="carousel-caption d-none d-md-block">
					<h5 class="text-white bg-dark">Visión</h5>
					<p class="font-monospace text-white bg-dark">
						Ser el Grupo líder en sustentabilidad a nivel nacional, integrado por personal <br>
						que vive los valores de ., comprometido con proporcionar soluciones <br>
						innovadoras a nuestros clientes, con tecnología de última generación..
					</p>
				</div>
			</div>
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Next</span>
		</button>
	</div>

	@*fin *@


	<!-- Content -->


	<section></section>
	<main></main>
	<script>

		function showSpinner() {
			$('.preloader').show();
		}

		// Función para ocultar el preloader
		function hideSpinner() {
			$('.preloader').hide();
		}

		document.addEventListener("DOMContentLoaded", function () {
			// Ocultar el preloader después de que la página se haya cargado completamente
			hidePreloader();
		});

		// Función para ocultar el preloader
		function hidePreloader() {
			document.querySelector(".preloader").style.display = "none";
		}
	</script>
</body>

</html>